CREATE TABLE students (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(30) UNIQUE NOT NULL,
    FOREIGN KEY (group_id) REFERENCES groups (id)
      ON DELETE SET NULL
      ON UPDATE CASCADE
);

CREATE TABLE groups (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(20) UNIQUE NOT NULL,
);

CREATE TABLE teachers (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(30) UNIQUE NOT NULL,
);

CREATE TABLE subjects (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(20) UNIQUE NOT NULL,
    FOREIGN KEY (teacher_id) REFERENCES teachers (id)
      ON DELETE SET NULL
      ON UPDATE CASCADE
);

CREATE TABLE scoreboard (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    mark INTEGER,
    date_ DATE NOT NULL
    FOREIGN KEY (subject_id) REFERENCES subjects (id)
      ON DELETE SET NULL
      ON UPDATE CASCADE
    FOREIGN KEY (student_id) REFERENCES students (id)
      ON DELETE SET NULL
      ON UPDATE CASCADE
);
